# Generated by Django 6.1.1 on 2026-09-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opis_id",
                    models.PositiveIntegerField(
                        help_text="OPIS Truckstop ID", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("rack_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=8, help_text="USD per gallon", max_digits=12
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "highways",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated Interstate/US routes, e.g. I-44,US-69",
                        max_length=255,
                    ),
                ),
                (
                    "geocode_precision",
                    models.CharField(
                        choices=[
                            ("city_centroid", "City centroid"),
                            ("exact", "Exact"),
                        ],
                        default="city_centroid",
                        max_length=20,
                    ),
                ),
                (
                    "source_row_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="CSV rows merged into this station (duplicates share an OPIS ID)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["opis_id"],
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"], name="fuelstation_lat_lon_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retail_price__gt", 0)),
                        name="fuelstation_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90),
                            ("latitude__lte", 90),
                            ("longitude__gte", -180),
                            ("longitude__lte", 180),
                        ),
                        name="fuelstation_coordinates_valid",
                    ),
                ],
            },
        ),
    ]
